In [ ]:
#generator
def linestyle_generator():
    linestyle = ["-","--","-.",":"]
    lineID = 0
    while True:
        print(lineID)
        yield linestyle[lineID]
        lineID = (lineID + 1) % len(linestyle)
LS = linestyle_generator()
for i in range(5):
    print(next(LS))

In [ ]:
t = (1,2,3,4,5)
r1 = [i for i in t]
print(r1)

In [ ]:
r2 = [i for i in t if i % 2 == 0]
print(r2)

In [ ]:
from numpy import sqrt
s = sum(x for x in range(1,51))
print(sqrt(s))

In [4]:
import numpy as np
A = np.array([[1,2],[-3,4]])
print(A)

[[ 1  2]
 [-3  4]]


In [5]:
print(A.T)

[[ 1 -3]
 [ 2  4]]


In [6]:
B = np.linalg.inv(A)
print(B)

[[ 0.4 -0.2]
 [ 0.3  0.1]]


In [7]:
np.linalg.det(A)

10.000000000000002

In [8]:
np.linalg.matrix_rank(A)

2

In [9]:
w, v = np.linalg.eig(A)
print("eigenvalue",w)
print("eigenvector=\n",v)

eigenvalue [2.5+1.93649167j 2.5-1.93649167j]
eigenvector=
 [[0.38729833-0.5j 0.38729833+0.5j]
 [0.77459667+0.j  0.77459667-0.j ]]


In [10]:
x = np.array([1,2])
print(x)
np.linalg.norm(x)

[1 2]


2.23606797749979

In [ ]:
Td = np.arange(0,10,1)
print(Td)